paths:
  raw: "./data/raw"
  cleaned: "./data/cleaned"
  sentiments: "./data/sentiments"

websites:
  isna:
    interval: 15
    start_date: 2025-12-04 17:32:49
    end_date:

  mehrnews:
    interval: 15
    start_date: 2025-12-04 17:32:49
    end_date:

  khabaronline:
    interval: 15
    start_date: 2025-12-04 17:32:49
    end_date:

  mashreghnews:
    interval: 15
    start_date: 2025-12-04 17:32:49
    end_date:

  tarafdari:
    interval: 15
    start_date: 2025-12-04 17:32:49
    end_date:
