paths:
  raw: "./data/raw"
  cleaned: "./data/cleaned"
  sentiments: "./data/sentiments"

websites:
  isna:
    interval: 15
    start_date: 2025-12-05 23:50:00
    end_date: 

  # mehrnews:
  #   interval: 15
  #   start_date: 2025-12-04 19:02:49
  #   end_date:

  # khabaronline:
  #   interval: 15
  #   start_date: 2025-12-04 19:02:49
  #   end_date:

  # mashreghnews:
  #   interval: 15
  #   start_date: 2025-12-04 19:02:49
  #   end_date:

  # tarafdari:
  #   interval: 15
  #   start_date: 2025-12-04 19:02:49
  #   end_date:

model:
  provider: "gemini"
  name: "gemini-2.5-pro"
  prompt_template_path: "config/prompt_template.txt"
