paths:
  raw: "./data/raw"
  cleaned: "./data/cleaned"
  sentiments: "./data/sentiments"

websites:
  isna:
    interval: 1
    start_date:
    end_date:

  mehrnews:
    interval: 1
    start_date:
    end_date:

  khabaronline:
    interval: 1
    start_date:
    end_date:

  mashreghnews:
    interval: 1
    start_date:
    end_date:

  tarafdari:
    interval: 1
    start_date:
    end_date:

  # spyder_name:
  #   interval: 1
  #   start_date: 2025-12-04 19:02:49
  #   end_date:

model:
  provider: "ollama"
  name: "gemma3:12b"
  prompt_template_path: "config/prompt_template.txt"
